export const ALL_PAPER_REQUEST = "ALL_PAPER_REQUEST";
export const ALL_PAPER_SUCCESS = "ALL_PAPER_SUCCESS";
export const ALL_PAPER_FAIL = "ALL_PAPER_FAIL";

export const ADMIN_PAPER_REQUEST = "ADMIN_PAPER_REQUEST";
export const ADMIN_PAPER_SUCCESS = "ADMIN_PAPER_SUCCESS";
export const ADMIN_PAPER_FAIL = "ADMIN_PAPER_FAIL";

export const UPDATE_PAPER_REQUEST = "UPDATE_PAPER_REQUEST";
export const UPDATE_PAPER_SUCCESS = "UPDATE_PAPER_SUCCESS";
export const UPDATE_PAPER_RESET = "UPDATE_PAPER_RESET";
export const UPDATE_PAPER_FAIL = "UPDATE_PAPER_FAIL";

export const DELETE_PAPER_REQUEST = "DELETE_CONTENT_REQUEST";
export const DELETE_PAPER_SUCCESS = "DELETE_CONTENT_SUCCESS";
export const DELETE_PAPER_RESET = "DELETE_CONTENT_RESET";
export const DELETE_PAPER_FAIL = "DELETE_CONTENT_FAIL";

export const NEW_PAPER_REQUEST = "NEW_PAPER_REQUEST";
export const NEW_PAPER_SUCCESS = "NEW_PAPER_SUCCESS";
export const NEW_PAPER_RESET = "NEW_PAPER_RESET";
export const NEW_PAPER_FAIL = "NEW_PAPER_FAIL";

export const PAPER_DETAILS_REQUEST = "PAPER_DETAILS_REQUEST";
export const PAPER_DETAILS_SUCCESS = "PAPER_DETAILS_SUCCESS";
export const PAPER_DETAILS_FAIL = "PAPER_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";